version: 0
versionshow: ""
downloadpathminlen: 88
Port: :9081
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
DefPassword: ""
DefSavePath: ""
StorehousePath: ""
DownloadPath: ""
P2PAddress: stsdsp2p1gl9ywg6jdfdgcja70ffum4ectq4fmt26n6z7tt
P2PPassword: aaa
WalletAddress: st1jn9skjsnxv26mekd8eu8a8aquh34v0m4mwgahg
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
BPURL: ""
IsCheckDefaultPath: false
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
IsCheckFileOperation: false
IsCheckFileTransferFinished: false
P2PKeyPrefix: stsdsp2p
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18091"
InternalPort: "9608"
SPList:
- P2PAddress: stsdsp2p162xm62m75cjv2529p7yydkxmqfwhknslen0wgt
  P2PPublicKey: stsdsp2p1zcjduepqnqrgs5cmwnhm2gg77xx3yghks80kgk72d65g37864ps7ualc6fsq20ssh4
  NetworkAddress: 0.0.0.0:8888
- P2PAddress: stsdsp2p1p0x879w88a2dlcymm4pl05aezf5tn0wue4mcah
  P2PPublicKey: stsdsp2p1zcjduepqppgzl9x2lr9hdu8vq9p6jx8y66xfsz4rkr6zhlumawz4ump6dp4qudcg27
  NetworkAddress: 0.0.0.0:18888
