version: 5
versionshow: v0.5.1
downloadpathminlen: 88
Port: "9081"
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: /Users/trexb/workspace/sds/example/network/node1/peers
AccountDir: /Users/trexb/workspace/sds/example/network/node1/accounts
StorehousePath: /Users/trexb/workspace/sds/example/network/node1/storage
DownloadPath: /Users/trexb/workspace/sds/example/network/node1/download
P2PAddress: stsds1gl9ywg6jdfdgcja70ffum4ectq4fmt26ay4znv
P2PPassword: aaa
WalletAddress: st1jn9skjsnxv26mekd8eu8a8aquh34v0m4mwgahg
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
RestPort: "18091"
InternalPort: "9608"
TrafficLogInterval: 10
SPList:
- P2PAddress: stsds14c3em44vlh276cujnr2ez802uyjyeqrrsu9fuh
  P2PPublicKey: stsdspub1zcjduepqzgqd566qdnj4kna050jz505vamjhglxcpdepqctkregdt6snxm6spxdk2l
  NetworkAddress: 127.0.0.1:18888
- P2PAddress: stsds1cw8qhgsxddak8hh8gs7veqmy5ku8f8za6qlq64
  P2PPublicKey: stsdspub1zcjduepqjmfc8j7ve0jg3jwq9wkefpa34fg9hhrp7nu6rkf6hff7ml769f6q676ryj
  NetworkAddress: 127.0.0.1:8888
- P2PAddress: stsds13yakj2xgzzdfcw7kd5gtfcfv2k6sn5eg4vdfem
  P2PPublicKey: stsdspub1zcjduepqhhplcrnkn9597gnh87y9zshe0kfs87fvmtrjpyq4heqjcz0dhltsys64es
  NetworkAddress: 127.0.0.1:38888
- P2PAddress: stsds15sya4n40da64z6n6hvk0p9f7sx72hqpjjnrf9y
  P2PPublicKey: stsdspub1zcjduepqpfr08evmk73dtf7ud69pwdznl4xdfghx6k6dyugwpk2jhqq890yq2nlm25
  NetworkAddress: 127.0.0.1:28888
