version: 0
versionshow: ""
downloadpathminlen: 88
Port: :9083
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
DefPassword: ""
DefSavePath: ""
StorehousePath: ""
DownloadPath: ""
P2PAddress: stsdsp2p1xg2jzku8gptq6sjpjd9zus8qec7a39phkvs84z
P2PPassword: aaa
WalletAddress: st142ndkgqu2earnvp28ur09dg62sd39xqwyux46a
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
BPURL: ""
IsCheckDefaultPath: false
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
IsCheckFileOperation: false
IsCheckFileTransferFinished: false
P2PKeyPrefix: stsdsp2p
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18093"
InternalPort: ""
SPList:
- P2PAddress: stsdsp2p162xm62m75cjv2529p7yydkxmqfwhknslen0wgt
  P2PPublicKey: stsdsp2p1zcjduepqnqrgs5cmwnhm2gg77xx3yghks80kgk72d65g37864ps7ualc6fsq20ssh4
  NetworkAddress: 0.0.0.0:8888
- P2PAddress: stsdsp2p1p0x879w88a2dlcymm4pl05aezf5tn0wue4mcah
  P2PPublicKey: stsdsp2p1zcjduepqppgzl9x2lr9hdu8vq9p6jx8y66xfsz4rkr6zhlumawz4ump6dp4qudcg27
  NetworkAddress: 0.0.0.0:18888
- P2PAddress: stsdsp2p1gee76xmy3d5ttgmnjx5enmexz4y3wu8w0q0rrf
  P2PPublicKey: stsdsp2p1zcjduepqvs62467hf02ahpja3ps8n9r4d2mm0c45s5pudkxqjhdnaxryqu8sprg297
  NetworkAddress: 0.0.0.0:28888
- P2PAddress: stsdsp2p15mwn0qa7faym4rsaxtufrhq4ul42pe2k2v66vg
  P2PPublicKey: stsdsp2p1zcjduepq3zzgzzttfu4jrqldyqnkyjm44p9kvyrfv8tdpmgpmz54djqfxfsqwdt3up
  NetworkAddress: 0.0.0.0:38888




